language: ruby
cache: bundler

rvm:
  - 2.3.7

addons:
  chrome: stable

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &



before_script: "bundle install"
before_script: "[ -d reports] && rm -rf reports"
before_script: "mkdir reports"


script: "bundle exec cucumber"


branches:
  only:
    - master

notifications:
  email:
    - bobycachoeira@gmail.com
