language: ruby
cache: bundler

rvm:
  - 2.3.7

addons:
  chrome: stable

#before_install:
 #- sudo apt-get update
 #- sudo apt-get install chromium-chromedriver

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3



before_script: "bundle install"
before_script: "[ -d reports] && rm -rf reports"
before_script: "mkdir reports"


script: "bundle exec cucumber"


branches:
  only:
    - master

notifications:
  email:
    - bobycachoeira@gmail.com
