language: ruby
cache: bundler

rvm:
  - 2.3.7


addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle install
  - [ -d reports] && rm -rf reports
  - mkdir reports



script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - bundle exec cucumber


branches:
  only:
    - master

notifications:
  email:
    - bobycachoeira@gmail.com
