language: ruby
cache: bundler

rvm:
  - 2.3.7

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

      
before_script:
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3


before_script: "bundle install"
before_script: "[ -d reports] && rm -rf reports"
before_script: "mkdir reports"


script: "bundle exec cucumber"


branches:
  only:
    - master

notifications:
  email:
    - bobycachoeira@gmail.com
